2019-08-30 09:50:31,247 INFO: Microblog startup [in C:\Users\Administrator\PycharmProjects\boke\app\__init__.py:35]
2019-08-30 09:53:50,405 INFO: Microblog startup [in C:\Users\Administrator\PycharmProjects\boke\app\__init__.py:35]
2019-08-30 09:57:29,304 INFO: Microblog startup [in C:\Users\Administrator\PycharmProjects\boke\app\__init__.py:35]
2019-08-30 09:59:08,371 INFO: Microblog startup [in C:\Users\Administrator\PycharmProjects\boke\app\__init__.py:35]
2019-08-30 10:02:06,858 INFO: Microblog startup [in C:\Users\Administrator\PycharmProjects\boke\app\__init__.py:35]
2019-08-30 10:02:40,348 INFO: Microblog startup [in C:\Users\Administrator\PycharmProjects\boke\app\__init__.py:35]
2019-08-30 10:08:52,185 INFO: Microblog startup [in C:\Users\Administrator\PycharmProjects\boke\app\__init__.py:35]
2019-08-30 10:26:35,856 INFO: Microblog startup [in C:\Users\Administrator\PycharmProjects\boke\app\__init__.py:35]
2019-08-30 10:35:36,771 INFO: Microblog startup [in C:\Users\Administrator\PycharmProjects\boke\app\__init__.py:35]
2019-08-30 10:36:06,319 INFO: Microblog startup [in C:\Users\Administrator\PycharmProjects\boke\app\__init__.py:35]
2019-08-30 10:37:29,275 INFO: Microblog startup [in C:\Users\Administrator\PycharmProjects\boke\app\__init__.py:35]
2019-08-30 10:37:42,802 INFO: Microblog startup [in C:\Users\Administrator\PycharmProjects\boke\app\__init__.py:35]
2019-08-30 10:41:05,908 INFO: Microblog startup [in C:\Users\Administrator\PycharmProjects\boke\app\__init__.py:35]
2019-08-30 10:46:23,842 INFO: Microblog startup [in C:\Users\Administrator\PycharmProjects\boke\app\__init__.py:35]
2019-08-30 10:46:29,142 ERROR: Exception on /user/zhangsan [GET] [in C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\flask\app.py:1780]
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\flask\app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\flask\app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\flask\app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\flask\_compat.py", line 36, in reraise
    raise value
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\flask\app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\flask\app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Administrator\PycharmProjects\boke\app\routes.py", line 106, in user
    return render_template('user.html', user=user, posts=posts.items, next_url=next_url, prev_url=prev_url)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Administrator\PycharmProjects\boke\app\templates\base.html", line 61, in template
    {% block scripts %}
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\jinja2\environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "C:\Users\Administrator\PycharmProjects\boke\app\templates\user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Administrator\PycharmProjects\boke\app\templates\base.html", line 61, in template
    {% block scripts %}
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\jinja2\environment.py", line 543, in _generate
    optimized=self.optimized)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\jinja2\compiler.py", line 82, in generate
    generator.visit(node)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\jinja2\visitor.py", line 38, in visit
    return f(node, *args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\jinja2\compiler.py", line 718, in visit_Template
    self.fail('block %r defined twice' % block.name, block.lineno)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\jinja2\compiler.py", line 315, in fail
    raise TemplateAssertionError(msg, lineno, self.name, self.filename)
jinja2.exceptions.TemplateAssertionError: block 'scripts' defined twice
2019-08-30 10:48:04,507 INFO: Microblog startup [in C:\Users\Administrator\PycharmProjects\boke\app\__init__.py:35]
